[build-system]
requires = [
    "setuptools>=53.1.0",
    "wheel>=0.36.2"
]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
version_variable = ['src/{{cookiecutter.project_name}}/__init__.py:__version__']
branch = "main"
upload_to_repository=false